#### que 1.   area of a triangle

In [ ]:
a=float(input("enter the value of arm:"))
b=float(input("enter the value of base:"))
area=1/2*(a*b)
print("the area is :", area)

##### taking multi input together

In [ ]:
a,b=[float(x) for x in input("enter the value of a and b:").split(',')]
area=1/2*(a*b)
print("the area is :", area)

#### que 2. Write a Python Program to Check if a Number is Positive, Negative or Zero.

In [ ]:
num=int(input("enter the numebr:"))
if num>0:
    print(" num is +ve")
elif num==0:
    print("num is zero")
else:
    print("num is -ve")

#### Program 3
Write a Python Program to Check if a Number is Odd or Even.


In [ ]:
num=int(input("enter the numebr:"))
if num%2==0:
    print("num is even")
else:
    print("num is odd")

#### Program 4
Write a Python Program to Check Leap Year.
This means that in a leap year, there are 366 days instead of the usual 365 days in a common year.

For example:

The year 2000 was a leap year because it is divisible by 4 and also by 400.
The year 2100 will not be a leap year even though it is divisible by 4 because it is not divisible by 100, unless it were also divisible by 400, which it is not.

In [ ]:
year = int(input("Enter a year: "))
# divided by 100 means century year (ending with 00)
# century year divided by 400 is leap year
if (year % 400 == 0) and (year % 100 == 0):
 print("{0} is a leap year".format(year))
# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
 print("{0} is a leap year".format(year))
# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
 print("{0} is not a leap year".format(year))

#### Program 5
Write a Python Program to Check Prime Number.

In [ ]:
# num=int(input("enter the num:")
# test_prime=[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
def prime(data):
    for num in test_prime:
        if (num==2 or num==3 or num==5):
            print(f"{num} this is prime")
        elif (num%2==0 or num%3==0 or num%5==0 or num==1):
            print(f"{num} not a prime")
        else:
            print(f"{num} this is prime")
    

In [ ]:
test_prime= [1, 2, 4, 7, 10, 13, 15, 17, 20, 23, 25, 29, 30, 31, 35, 37, 40, 41, 45, 47, 50]
print(prime(test_prime))


#### Program 
Write a Python Program to Find the Factorial of a Number

In [ ]:
## method -1
num=int(input("enter the numebr:"))
res=1
for num in range(1, num+1):
    res=res*num
print(res)
    

In [ ]:
## method -2
## using recursion techniques
def fact(x):
    if x>1:
        return x*fact(x-1)
    else:
        return 1
    

In [ ]:
x=5
print(fact(x))

#### Program 
Write a Python Program to Print the Fibonacci sequence.

In [ ]:
nterms = int(input("How many terms? "))
# first two terms
n1, n2 = 0, 1
count = 0
# check if the number of terms is valid
if nterms <= 0:
 print("Please enter a positive integer")
# if there is only one term, return n1
elif nterms == 1:
    print("Fibonacci sequence upto",nterms,":")
    print(n1)
# generate fibonacci sequence
else:
    print("Fibonacci sequence:")
    while count < nterms:
        print(n1, end=' ')
        nth = n1 + n2
         # update values
        n1 = n2
        n2 = nth
        count += 1

#### above method hacve T.C. O(n)

In [ ]:
## method -2

def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)

# get the number of terms from the user
n = int(input("Enter the number of terms: "))

# print the first n terms of the series
for i in range(n):
    print(fibonacci(i), end='  ')

#### #### above method hacve T.C. O(2^n)

#### Program
Write a Python Program to Find Armstrong Number in an Interval.

In [3]:
# def lennum(n):  # function to check the digit in given number
#     count=0
#     while n>0:
#         n=n//10
#         count+=1
#     return count

def lennum(n):  # aanother method or function to check the digit in given number
    count=len(str(n))
    return count
    

def Isarmstrong(n, r):
    res=0
    while n>0:
        rem=n%10
        res+=rem**r
        n=n//10
    return res

In [5]:
min_value, max_value=[int(x) for x in input("the range:").split(',')]
for x in range(min_value, max_value, 1):
    n=x
    len_num=lennum(n)
#     print(len_num)
    result=Isarmstrong(n, len_num)
    if n==result:
        print(f" {n} is Armstrong Number")
    else:
        continue
        
    

the range:10, 200
 153 is Armstrong Number



#### understand what is GCD (HCF) and LCM
Let's find the LCM, GCD, and HCF of two numbers: 12 and 18.

1. GCD (Greatest Common Divisor):
The GCD of two numbers is the largest positive integer that divides both numbers without leaving a remainder.

For 12 and 18:

Factors of 12: 1, 2, 3, 4, 6, 12
Factors of 18: 1, 2, 3, 6, 9, 18
The largest common factor is 6. Therefore, GCD(12, 18) = 6.

2. HCF (Highest Common Factor):
HCF is another term for GCD. So, HCF(12, 18) = 6 (same as GCD).

3. LCM (Least Common Multiple):
The LCM of two numbers is the smallest positive integer that is divisible by both numbers.

For 12 and 18:

Multiples of 12: 12, 24, 36, 48, ...
Multiples of 18: 18, 36, 54, 72, ...
The smallest common multiple is 36. Therefore, LCM(12, 18) = 36.

###### Formula:
For two numbers a and b, the LCM can be found using the formula:
For more than two numbers, you can find the LCM step by step, taking the LCM of pairs of
numbers at a time until you reach the last pair.
Note: GCD stands for Greatest Common Divisor.

LCM(𝑎, 𝑏) =
(𝑎 ⋅ 𝑏)/ GCD(𝑎, 𝑏)

#### Write a Python Program to Find LCM.

In [6]:
# Python Program to find the L.C.M. of two input number
def compute_lcm(x, y):
 if x > y: # choose the greater number
    greater = x
 else:
     greater = y
 while(True):
    if((greater % x == 0) and (greater % y == 0)):
        lcm = greater
        break
    greater += 1
 return lcm

num1 = int(input('Enter the number: '))
num2 = int(input('Enter the number: '))
print("The L.C.M. is", compute_lcm(num1, num2))

Enter the number: 12
Enter the number: 18
The L.C.M. is 36


#### Write a Python Program to Find HCF or GCD

In [7]:
# Python program to find H.C.F of two numbers
# define a function
def compute_hcf(x, y):
    if x > y:
        smaller = y
    else:
        smaller = x
    for i in range(1, smaller+1):
        if((x % i == 0) and (y % i == 0)):
            hcf = i
    return hcf
num1 = int(input('Enter the number: '))
num2 = int(input('Enter the number: '))
print("The H.C.F. is", compute_hcf(num1, num2))

Enter the number: 12
Enter the number: 18
The H.C.F. is 6


#### Write a Python Program to find sum of array.


In [ ]:
array=[12, 34, 45, 68, 1102,  87, 4646, 6]
res=0
for s in array:
    res+=s
print(res)

#### Write a Python Program to find largest element in an array.


In [ ]:
xmax=array[0]
for s in range(1, len(array)):
    if array[s]>xmax:
        xmax=array[s]
    else:
        continue
print(f"{xmax} is largest")

#### Write a Python Program to find minimum element in an array

In [ ]:
xmin=array[0]
for s in range(1, len(array)):
    if array[s]<xmin:
        xmin=array[s]
    else:
        continue
print(f"{xmin} is smallest")

#### write a python program for array rotation

In [8]:
arr = [1, 2, 3, 4, 5, 6, ]

for i in range(0, len(arr)//2):  #The loop now only needs to iterate up to half of the array length 
    ## since you are swapping elements symmetrically.
    temp = arr[i]
    arr[i] = arr[len(arr) - 1 - i]
    arr[len(arr) - 1 - i] = temp

print(arr)


[6, 5, 4, 3, 2, 1]


### Write a Python Program to Split the array and add the first part to the end?

In [9]:
def split_and_add(arr, k):
    if k <= 0 or k >= len(arr):
        return arr 
 # Split the array into two parts
    first_part = arr[:k]
    second_part = arr[k:]
 # Add the first part to the end of the second part
    result = second_part + first_part
    return result
# Test the function
arr = [1, 2, 3, 4, 5]
k = 3
result = split_and_add(arr, k)
print("Original Array:", arr)
print("Array after splitting and adding:", result)


Original Array: [1, 2, 3, 4, 5]
Array after splitting and adding: [4, 5, 1, 2, 3]


#### Write a Python Program to Remove Punctuation From a String.


In [10]:
# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
# To take input from the user
my_str = input("Enter a string: ")
# remove punctuation from the string
no_punct = ""
for char in my_str:
    if char not in punctuations:
        no_punct = no_punct + char
# display the unpunctuated string
print(no_punct)


Enter a string: hdgwgu dbudw9i0b t6bf.g'pg;mle g
hdgwgu dbudw9i0b t6bfgpgmle g


#### Write a Python program to find second largest number in a list.


In [11]:
# Sample list of numbers
numbers = [30, 10, 45, 5, 20]
# Sort the list in descending order
numbers.sort(reverse=True)
# Check if there are at least two elements in the list
if len(numbers) >= 2:
    second_largest = numbers[1]
    print("The second largest number in the list is:", second_largest)
else:
    print("The list does not contain a second largest number.")


The second largest number in the list is: 30


In [12]:
### method -2

def find_second_largest(numbers):
    if len(numbers) < 2:
        return "List must have at least two numbers."

    largest = second_largest = float('-inf')

    for num in numbers:
        if num > largest:
            second_largest = largest
            largest = num
        elif num > second_largest and num != largest:
            second_largest = num

    return second_largest

# Example usage
num_list = [3, 1, 7, 4, 5, 6, 2]
result = find_second_largest(num_list)

if isinstance(result, str):
    print(result)
else:
    print(f"The second largest number is: {result}")


The second largest number is: 6


###### method -3 (most preferred)

In [13]:
### method -3

def find_second_largest(numbers):
    if len(numbers) < 2:
        return "List must have at least two numbers."

    largest = numbers[0]
    second_largest=numbers[0]

    for num in numbers:
        if num > largest:
            largest = num
    for num in numbers:
        if (num>second_largest and num!=largest):
            second_largest=num
    return second_largest

# Example usage
num_list = [3, 1, 7, 4, 5, 6, 2]
result = find_second_largest(num_list)
print(f"The second largest number is: {result}")


The second largest number is: 6


#### Write a Python program to print even numbers in a list.
##### using list comprehension

##### List comprehension is a concise way to create lists in Python. It provides a compact syntax for generating lists by applying an expression to each item in an iterable (e.g., a list, tuple, or range) and optionally filtering the items based on a condition.

The basic syntax of a list comprehension is as follows:


###### [expression for item in iterable if condition]
Here, expression is the operation or transformation to be applied to each item, item is the variable representing each element in the iterable, and condition is an optional filter.

In [14]:
ls=[12, 4, 56, 45, 23, 55, 68]

res=[num for num in ls if num%2==0]  # list comprehension
res

[12, 4, 56, 68]

In [15]:
## OR

ls=(12, 4, 56, 45, 23, 55, 68)

res=[num for num in ls if num%2==0]  # list comprehension
res

[12, 4, 56, 68]

In [16]:
## OR using filter() function

def func(num):
    if num%2==0:
        return num
    
res=filter(func, ls)
print(list(res))

## OR usng lambda()

res1=filter(lambda x: x%2==0, ls)
list(res1)

[12, 4, 56, 68]


[12, 4, 56, 68]

#### Write a Python program to Remove empty List from List.




In [17]:
# Sample list containing lists
list_of_lists = [[1, 2, 3], [], [4, 5], [], [6, 7, 8], []]
res=[x for x in list_of_lists if len(x)!=0]
res

[[1, 2, 3], [4, 5], [6, 7, 8]]

In [18]:
## method -2

#Sample list containing lists
list_of_lists = [[1, 2, 3], [], [4, 5], [], [6, 7, 8], []]
# Using a list comprehension to remove empty lists
filtered_list = [i for i in list_of_lists if i]
# Print the filtered list
print("List after removing empty lists:", filtered_list)


List after removing empty lists: [[1, 2, 3], [4, 5], [6, 7, 8]]


#### Write a Python program to Count occurrences of an element in a list.

In [19]:
# method -1 using count() method
a=[1,2,3,4,5,6,2,3,3,3]
res=a.count(3)
res

4

In [20]:
# method -2
num=3
count=0
for x in a:
    if num==x:
        count+=1
print(count)
    


4


#### Write a Python program for removing 𝑖 character from a string.

In [21]:
s="Hello, wWorld!"
i=7 # removing 5th indexed elment

    
res=list(s)  ## will split in individual character

# res=res.pop(i) it stores the delelted element 

res.pop(i)

result_string = ''.join(res)

result_string

'Hello, World!'

#### Write a Python program to split and join a string

In [22]:
x=str(input("enter the string:"))

# split
x=x.split()
# print(x)
x=' '.join(x)
x

enter the string:hi danbfu ubsd j


'hi danbfu ubsd j'

#### Write a Python program to find uncommon words from two Strings.

In [23]:
str1="my name is shrawan"
str2="my name is sandeep"

# checking i str1
for x in str1.split():
    if x in str2.split():
        continue
    else:
        print(x)
# checking i str2    
for x in str2.split():
    if x in str1.split():
        continue
    else:
        print(x)
        

shrawan
sandeep


##### method -2 (most preffered)


In [24]:
## conerting into set

st1=set(str1.split())
st2=set(str2.split())

res=(st1.union(st2)) - (st1.intersection(st2))   ##   st1.symmetric_difference(st2)  ## we can use this func also
for x in res:
    print(x)

sandeep
shrawan


#### Write a Python program to find all duplicate characters with their counts in string.

In [25]:
s = "shrawan kumawat jhunjhunu"
processed_chars = set()

for i in range(0, len(s)):
    if s[i] in processed_chars or s[i].isspace():
        continue  # Skip characters that have already been processed or are spaces
    count = 0
    for j in range(i, len(s)):
        if s[j] == s[i] and i != j:
            count += 1
    if count > 0:
        print(f"{s[i]} is {count} times duplicate")
        processed_chars.add(s[i]) # save the charcter that have been processed


h is 2 times duplicate
a is 3 times duplicate
w is 1 times duplicate
n is 2 times duplicate
u is 3 times duplicate
j is 1 times duplicate


#### Write a Python program to find all duplicate characters in string.

In [26]:
s = "shrawan kumawat jhunjhunu"
processed_chars = set()
dup_char=[]
for i in range(0, len(s)):
    if s[i] in processed_chars or s[i].isspace():
        continue  # Skip characters that have already been processed or are spaces
    count = 0
    for j in range(i, len(s)):
        if s[j] == s[i] and i != j:
            count += 1
    if count > 0:
        dup_char.append(s[i])
        processed_chars.add(s[i]) # save the charcter that have been processed
        
print(dup_char)


['h', 'a', 'w', 'n', 'u', 'j']


#### Write a Python Program to check if a string contains any special characte

In [27]:
import re

def check_special_char(in_str):
    # Define a regular expression pattern to match special characters
    pattern = r'[!@#$%^&*()_+{}\[\]:;<>,.?~\\\/\'"\-=]'
 # Use re.search to find a match in the input string
    if re.search(pattern, in_str):
        return True
    else:
        return False
# Input a string
input_string = str(input("Enter a string: "))
# Check if the string contains any special characters
contains_special = check_special_char(input_string)
# Print the result
if contains_special:
 print("The string contains special characters.")
else:
 print("The string does not contain special characters.")


Enter a string: hudof fubiw f
The string does not contain special characters.


#### Write a Python program to Merging two Dictionaries.


In [28]:
# 1. Using the update() method:
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
dict1.update(dict2)
# The merged dictionary is now in dict1
print("Merged Dictionary (using update()):", dict1)

Merged Dictionary (using update()): {'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [29]:
# 2. Using dictionary unpacking
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
# Merge dict2 into dict1 using dictionary unpacking
merged_dict = {**dict1, **dict2}
# The merged dictionary is now in merged_dict
print("Merged Dictionary (using dictionary unpacking):", merged_dict)


Merged Dictionary (using dictionary unpacking): {'a': 1, 'b': 2, 'c': 3, 'd': 4}


#### Write a Python program to convert key-values list to flat dictionary.

In [30]:
key_values_list = [('a', 1), ('b', 2), ('c', 3), ('d', 4)]
# Initialize an empty dictionary
flat_dict = {}
# Iterate through the list and add key-value pairs to the dictionary
for key, value in key_values_list:
 flat_dict[key] = value
# Print the resulting flat dictionary
print("Flat Dictionary:", flat_dict)

Flat Dictionary: {'a': 1, 'b': 2, 'c': 3, 'd': 4}


#### Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional
array. The element value in the i-th row and j-th column of the array should be i*j.

Note: i=0,1.., X-1; j=0,1,¡Y-1.

Example

Suppose the following inputs are given to the program:

3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


#### Note taking input using map() function

##### Input two digits, X and Y
X, Y = map(int, input("Enter two digits (X, Y): ").split(','))


In [31]:
import numpy as np

def array(x, y, arr):
    for i in range(0, x):
        for j in range(0, y):
            arr[i][j]=i*j
    return arr
    

x, y=[int(x) for x in input("enter the values (rows, col):").split(',')]

arr=np.zeros([x,y], dtype=int)

res=array(x, y, arr)
print(res)

enter the values (rows, col):12,4
[[ 0  0  0  0]
 [ 0  1  2  3]
 [ 0  2  4  6]
 [ 0  3  6  9]
 [ 0  4  8 12]
 [ 0  5 10 15]
 [ 0  6 12 18]
 [ 0  7 14 21]
 [ 0  8 16 24]
 [ 0  9 18 27]
 [ 0 10 20 30]
 [ 0 11 22 33]]


In [32]:
## we can initialize empty array also   np.empty([m, n], dtype=int)
import numpy as np

def array(x, y, arr):
    for i in range(0, x):
        for j in range(0, y):
            arr[i][j]=i*j
    return arr
    

x, y=[int(x) for x in input("enter the values (rows, col):").split(',')]

arr=np.empty([x,y], dtype=int)

res=array(x, y, arr)
print(res)

enter the values (rows, col):4, 3
[[0 0 0]
 [0 1 2]
 [0 2 4]
 [0 3 6]]


### very imoprtant (must seee)

#### Write a program that accepts a comma separated sequence of words as input and
prints the words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world

Then, the output should be:

bag,hello,without,world

In [32]:
## method -01
words=[x for x in input().split(',')]
sort_w=sorted(words)
result=','.join(sort_w)
print(result)
print("\n")

result

without,hello,bag,world
bag,hello,without,world




'bag,hello,without,world'

In [25]:
## method -02

# Accept input from the user
input_sequence = input("Enter a comma-separated sequence of words: ")
# Split the input into a list of words
words = input_sequence.split(',')
# Sort the words alphabetically
sorted_words = sorted(words)
# Join the sorted words into a comma-separated sequence
sorted_sequence = ','.join(sorted_words)
# Print the sorted sequence
print("Sorted words:", sorted_sequence)


Enter a comma-separated sequence of words: hii, thid, is 
Sorted words:  is , thid,hii


#### Write a program that accepts a sequence of whitespace separated words as input

and prints the words after removing all duplicate words and sorting them
alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world

In [29]:
input_word=input("enter the wrods by whitespace")
words=input_word.split(' ')

words=set(words)
words=sorted(words)
words=' '.join(words)
print(words)


enter the wrods by whitespacehello world and practice makes perfect and hello world again
again and hello makes perfect practice world


#### Write a program that accepts a sentence and calculate the number of letters and
digits. Suppose the following input is supplied to the program:

hello world! 123

Then, the output should be:

LETTERS 10

DIGITS 3


In [34]:
# Accept input from the user
sentence = input("Enter a sentence: ")
# Initialize counters for letters and digits
letter_count = 0
digit_count = 0
# Iterate through each character in the sentence
for char in sentence:
    if char.isalpha():
        letter_count += 1
    elif char.isdigit():
        digit_count += 1
# Print the results
print("LETTERS", letter_count)
print("DIGITS", digit_count)


Enter a sentence: gii gaj hii* 90 by8
LETTERS 11
DIGITS 3


### Note : very imp concept
 If you want to input values for "name" and "roll number" in multiple rounds and store them in the dictionary, you can use a loop to iteratively take user input and update the dictionary. Here's an example:



In [39]:
# Create an empty dictionary
my_dict = {}

# List of keys
keys = ["name", "roll number"]

# Input values in multiple rounds
for _ in range(2):  # Assuming two rounds, you can adjust as needed
    # Input values for each key
    for key in keys:
        value = input(f"Enter {key}: ")
        # Store the value in the dictionary
        my_dict.setdefault(key, []).append(value)

# Print the resulting dictionary
print("\n")
print(my_dict)


Enter name: shrawan
Enter roll number: 1201
Enter name: sandeep
Enter roll number: 1202


{'name': ['shrawan', 'sandeep'], 'roll number': ['1201', '1202']}


In [40]:
# Accept input from the user
sentence = input("Enter a sentence: ")

# Initialize counters for letters, digits, special characters, and punctuation
letter_count = 0
digit_count = 0
special_char_count = 0
punctuation_count = 0

# Initialize a dictionary to store counts
result = {}

# Iterate through each character in the sentence
for char in sentence:
    if char.isalpha():
        result.setdefault('Letters', []).append(char)
        letter_count += 1
    elif char.isdigit():
        result.setdefault('Digits', []).append(char)
        digit_count += 1
    elif char.isspace():
        # Skip counting spaces, you may adjust this based on your requirements
        pass
    elif char.isalnum():
        # If the character is alphanumeric, it's not a special character or punctuation
        pass
    else:
        # Check if the character is a special character or punctuation
        result.setdefault('Special Characters', []).append(char)
        special_char_count += 1
        if char in ",.!?;:":
            # If you have specific punctuation characters to check, add them here
            result.setdefault('Punctuation', []).append(char)
            punctuation_count += 1

# Print the results
print("LETTERS:", letter_count)
print("DIGITS:", digit_count)
print("SPECIAL CHARACTERS:", special_char_count)
print("PUNCTUATION:", punctuation_count)
print("Result Dictionary:", result)


Enter a sentence: hi dueb 899 kfjo090)() %^^ (, fjubf
LETTERS: 15
DIGITS: 6
SPECIAL CHARACTERS: 8
PUNCTUATION: 1
Result Dictionary: {'Letters': ['h', 'i', 'd', 'u', 'e', 'b', 'k', 'f', 'j', 'o', 'f', 'j', 'u', 'b', 'f'], 'Digits': ['8', '9', '9', '0', '9', '0'], 'Special Characters': [')', '(', ')', '%', '^', '^', '(', ','], 'Punctuation': [',']}


#### A website requires the users to input username and password to register. Write a program to check the validity of password input by users. Following are the criteria
for checking the password:

1. At least 1 letter between [a-z]

2. At least 1 number between [0-9]

1. At least 1 letter between [A-Z]

3. At least 1 character from [$#@]

4. Minimum length of transaction password: 6

5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will
check them according to the above criteria. Passwords that match the criteria are to
be printed, each separated by a comma.

Example
If the following passwords are given as input to the program:

ABd1234@1,a F1#,2w3E*,2We3345

Then, the output of the program should be:

ABd1234@1

In [41]:
import re
# Function to check if a password is valid
def is_valid_password(password):
    # Check the length of the password
    if 6 <= len(password) <= 12:
        # Check if the password matches all the criteria using regular 
        if re.match(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[$#@])", password):
            return True
    return False
# Accept input from the user as comma-separated passwords
passwords = input("Enter passwords separated by commas: ").split(',')
# Initialize a list to store valid passwords
valid_passwords = []
# Iterate through the passwords and check their validity
for psw in passwords:
    if is_valid_password(psw):
        valid_passwords.append(psw)
# Print the valid passwords separated by commas
print(','.join(valid_passwords))

Enter passwords separated by commas: ABd1234@1,a F1#,2w3E*,2We3345
ABd1234@1


#### Define a class with a generator which can iterate the numbers, which are divisible by 7, between a given range 0 and n.


In [4]:
class DivSeven:
    def __init__(self, n):
        self.n=n
    def func(self):
        for i in range(1, self.n):
            if i%7==0:
                yield i
    

In [5]:
n=int(input("enter the value:"))
obj=DivSeven(n)
num=obj.func()
for n in num:
    print(n)

enter the value:100
7
14
21
28
35
42
49
56
63
70
77
84
91
98


#### Write a program to compute the frequency of the words from the input. The output
should output after sorting the key alphanumerically. Suppose the following input is
supplied to the program:

New to Python or choosing between Python 2 and Python 3? Read Python 2 or
Python 3.

Then, the output should be:

2:2

3.:1

3?:1

New:1

Python:5

Read:1

and:1

between:1

choosing:1

or:2

to:1

In [15]:
x="shrawan&)"
y=x.strip('&)')
y

'shrawan'

In [18]:
input_sentence = input("Enter a sentence: ")
# Split the sentence into words
words = input_sentence.split()
# Create a dictionary to store word frequencies
word_freq = {}
# Count word frequencies
for word in words:
    # Remove punctuation (., ?) from the word
#     word = word.strip('.,?')                                   ## removes punc fro end of the string words
 # Convert the word to lowercase to ensure case-insensitive counting
    word = word.lower()
     # Update the word frequency in the dictionary
    if word in word_freq:
        word_freq[word] += 1
    else:
        word_freq[word] = 1
# Sort the words alphanumerically
sorted_words = sorted(word_freq.items())
# Print the word frequencies
for word, frequency in sorted_words:
    print(f"{word}:{frequency}")


Enter a sentence: New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3.
2:2
3.:1
3?:1
and:1
between:1
choosing:1
new:1
or:2
python:5
read:1
to:1


#### Define a class Person and its two child classes: Male and Female. All classes have a method "getGender" which can print "Male" for Male class and "Female" for Female class.


In [26]:
class Person:
    def __init__(self):
        pass
class Male(Person):
    def getGender(self):
        print("this Male")
class Female(Person):
    def getGender(self):
        print("This is Female")
        
objM=Male()
objF=Female()

print(objM.getGender())
print(objF.getGender())
        

this Male
None
This is Female
None


In [27]:
## or 
class Person:
    def getGender(self):
        return "Unknown"
class Male(Person):
    def getGender(self):
        return "Male"
class Female(Person):
    def getGender(self):
        return "Female"
    
person = Person()
male = Male()
female = Female()
print(person.getGender()) 
print(male.getGender()) 
print(female.getGender()) 


Unknown
Male
Female


#### Please write a binary search function which searches an item in a sorted list. The
function should return the index of element to be searched in the list.

##### when list is not sorted

In [28]:
def func(ls, k):
    for i in range(0, len(ls)):
        if ls[i]==k:
            return i
        else:
            continue

ls=[12, 5, 6, 45, 6, 89, 65]
print(func(ls, 89))
    

5


##### Using binary search algo *(when we have sorted list and its T.C. O(logn)

In [29]:
def binary_search(arr, target):
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid # Element found, return its index
        elif arr[mid] < target:
            left = mid + 1 # Target is in the right half
        else:
             right = mid - 1 # Target is in the left half
    return -1 # Element not found in the list
# Example usage:
sorted_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
target_element = 4
result = binary_search(sorted_list, target_element)
if result != -1:
 print(f"Element {target_element} found at index {result}")
else:
 print(f"Element {target_element} not found in the list")

Element 4 found at index 3


### based on generator (must see)

#### Please write a program using generator to print the numbers which can be divisible by 5 and 7 between 0 and n in comma separated form while n is input by console.
Example:

If the following n is given as input to the program:

100

Then, the output of the program should be:

0,35,70

In [1]:
def func(n):
    for i in range(0, n+1):
        if i%7==0 and i%5==0:
            yield i
        

In [3]:
try:
    n = int(input("Enter a value for n: "))
    result = func(n)
    print(','.join(map(str, result)))
except ValueError:
    print("Invalid input. Please enter a valid integer for n.")

Enter a value for n: 200
0,35,70,105,140,175


#### Please write a program using generator to print the even numbers between 0 and n in
comma separated form while n is input by console.


In [4]:
def func(n):
    for i in range(0, n+1):
        if i%2==0:
            yield i
try:
    n = int(input("Enter a value for n: "))
    result = func(n)
    print(','.join(map(str, result)))
except ValueError:
    print("Invalid input. Please enter a valid integer for n.")

Enter a value for n: 20
0,2,4,6,8,10,12,14,16,18,20


#### Assuming that we have some email addresses in the

"username@companyname.com (mailto:username@companyname.com)" format,

please write program to print the user name of a given email address. Both user
names and company names are composed of letters only.

Example:

If the following email address is given as input to the program:

john@google.com (mailto:john@google.com)

Then, the output of the program should be:

john


In [6]:
def extract_username(email):
    # Split the email address at '@' to separate the username and domai
    parts = email.split('@')
 
 # Check if the email address has the expected format
    if len(parts) == 2:
        return parts[0] # The username is the first part
    else:
        return "Invalid email format"

In [8]:
try:
 email = input("Enter an email address: ")
 username = extract_username(email)
 print(username)
except ValueError:
 print("Invalid input. Please enter a valid email address.")


Enter an email address: rahulzaware2018@gmail.com
rahulzaware2018


#### Define a class named Shape and its subclass Square. The Square class has an init function which takes a length as argument. Both classes have an area function which can print the area of the shape where Shape's area is 0 by default.

In [9]:
class Shape:
    def __init__(self):
        pass # Default constructor, no need to initialize anything
    def area(self):
        return 0 # Shape's area is 0 by default
class Square(Shape):
        def __init__(self, length):
            super().__init__() # Call the constructor of the parent class
            self.length = length
        def area(self):
            return self.length ** 2 # Calculate the area of the square

In [10]:
# Create instances of the classes
shape = Shape()
square = Square(float(input("Enter the shape of the square: ")))
# Calculate and print the areas
print("Shape's area by default:", shape.area()) 
print("Area of the square:", square.area()) 

Enter the shape of the square: 10
Shape's area by default: 0
Area of the square: 100.0
