In [1]:
import numpy as np

In [9]:
import numpy as np
a=np.array([1,2,3,4,5,6,0.2]) #this means np array can store different data types
print(a)
print(type(a))
print(len(a))
print(a.ndim)

[1.  2.  3.  4.  5.  6.  0.2]
<class 'numpy.ndarray'>
7
1


In [11]:
import numpy as np
a=np.array([1,2,3,4,'Ram',6,0.2]) #this means np array can store different data types
print(a)
print(type(a))
print(len(a))
print(a.ndim)

print("\n")

for x in a:
    print(type(x))

['1' '2' '3' '4' 'Ran' '6' '0.2']
<class 'numpy.ndarray'>
7
1


<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### add  items to array
#### Method 1st is: by converting in list

In [3]:
b=list(a)

In [4]:
type(b)

list

In [5]:
b.append(6)

In [6]:
b

['1', '2', '3', '4', '5', 'ram', '0.2', 6]

In [7]:
c=np.array(b)

In [8]:
type(c)

numpy.ndarray

In [9]:
c

array(['1', '2', '3', '4', '5', 'ram', '0.2', '6'], dtype='<U11')

#### method 2 

In [10]:
a

array(['1', '2', '3', '4', '5', 'ram', '0.2'], dtype='<U32')

In [11]:
new1=np.append(a, 7)

In [12]:
new1

array(['1', '2', '3', '4', '5', 'ram', '0.2', '7'], dtype='<U32')

## creating multideimensional array

In [6]:
b=np.array([[1,2,3,4,5],[3,3,4,6,7],[3,2,4,5,5]])
print(b)
print(b.shape)
print(len(b))
print("size is:",b.size)
print(b.ndim)
print(type(b))

[[1 2 3 4 5]
 [3 3 4 6 7]
 [3 2 4 5 5]]
(3, 5)
3
size is: 15
2
<class 'numpy.ndarray'>


In [8]:
#reshape
a2=b.reshape(5,3)
print(a2)
print("\n")

a2=b.reshape(-1,5) #-ve values adjust the array accordingly
print(a2)

[[1 2 3]
 [4 5 3]
 [3 4 6]
 [7 3 2]
 [4 5 5]]


[[1 2 3 4 5]
 [3 3 4 6 7]
 [3 2 4 5 5]]


#### Create numpy array using nested list

In [15]:
l1=[1,2,3,4]
l2=[2,3,4,5]
l3=[4,4,6,7]
a3=np.array([l1,l2,l3],dtype=int)    #can change data type like this
print(a3)

[[1 2 3 4]
 [2 3 4 5]
 [4 4 6 7]]


### numpy attributes

In [16]:
a3=np.arange(1.0,2.0,0.25)
print(a3)
print(a3.shape)

[1.   1.25 1.5  1.75]
(4,)


In [17]:
a4=np.arange(24)
print(a4)
a5=a4.reshape(2,4,3) # 4X3 matrix with len 2
print(a5)
print(len(a5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
2


##### numpy array arithmetic operation

In [18]:
b1=np.array([[1,2,3],[4,5,6]])
b2=np.array([[7,8,9],[9,8,7]])
print(b1+b2)
print(np.subtract(b1,b2))
print(b1*b2)
print(np.divide(b1,b2))
print(b2%b1)
print(b1**b2)
print(np.power(b1,b2))

[[ 8 10 12]
 [13 13 13]]
[[-6 -6 -6]
 [-5 -3 -1]]
[[ 7 16 27]
 [36 40 42]]
[[0.14285714 0.25       0.33333333]
 [0.44444444 0.625      0.85714286]]
[[0 0 0]
 [1 3 1]]
[[     1    256  19683]
 [262144 390625 279936]]
[[     1    256  19683]
 [262144 390625 279936]]


In [20]:
#sum
b11=np.array([[1,2,3], [4,5,6]])
b12=np.array([[7,8,9], [10,11,12]])
print(np.sum(b11))
print(np.sum(b11,axis=0)) #sum of each col
print(np.sum(b11,axis=1)) #sum of each row


21
[5 7 9]
[ 6 15]


In [22]:
d=np.linspace(5,16,10) #range from 5 to 16 with 10 equal parts
print(d)

[ 5.          6.22222222  7.44444444  8.66666667  9.88888889 11.11111111
 12.33333333 13.55555556 14.77777778 16.        ]


In [23]:
#iteration  numpy array
for x in np.nditer(a):
  print(x, end=' ')
print("\n")

# Or we can write like this
for x in a:
  print(x, end=' ')

1 2 3 4 5 ram 0.2 

1 2 3 4 5 ram 0.2 

In [24]:
a

array(['1', '2', '3', '4', '5', 'ram', '0.2'], dtype='<U32')

In [25]:
b1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.max(b1, axis=1) #returns rows max

array([3, 6])

In [27]:
a=np.zeros(2, dtype=int)
a

array([0, 0])

In [28]:
b24=np.zeros([2,3])
b24

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
b231=np.zeros([3, 2, 4])
b231

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
c=np.full((3,2),15)
c

array([[15, 15],
       [15, 15],
       [15, 15]])

In [31]:

d=np.random.rand(12)
d

array([0.09528993, 0.80471184, 0.35750269, 0.4250106 , 0.73240109,
       0.53219144, 0.67632438, 0.10877619, 0.94094233, 0.31300647,
       0.1956067 , 0.51016943])

In [32]:
np.random.randn(12)

array([-1.33458505, -0.141009  , -0.14691214, -1.10759182,  0.38921122,
        1.5265517 , -1.11816164, -0.54935742, -0.16158694, -2.43132268,
       -0.27611995, -3.05473896])

In [33]:
np.random.randint(1, 50, 20)

array([ 4,  9, 45, 21, 27, 13, 38, 26, 18, 49, 30, 23, 12,  8, 49, 44,  9,
       28, 43, 16])

In [36]:
np.random.normal(size=4)

array([ 0.61111663,  0.42793951, -0.52870748,  0.07481555])

In [44]:
np.random.uniform(size=12)

array([0.5235698 , 0.89066239, 0.46613516, 0.5429559 , 0.6239564 ,
       0.55123375, 0.00786825, 0.26428386, 0.22582764, 0.4603738 ,
       0.366049  , 0.36900757])

In [46]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [49]:
np.ones((4,4), dtype =int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [50]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [53]:
x=np.append(x, 6)

In [54]:
x

array([1, 2, 3, 4, 5, 6])

In [55]:
x=np.insert(x, 4, 7)

In [56]:
x

array([1, 2, 3, 4, 7, 5, 6])

In [60]:
x=np.delete(x, 2, axis=0)

In [61]:
x

array([1, 2, 7, 5, 6])

In [12]:
a=np.array([[1,2,3], [4,5,6]])
b=np.array([[7,8,9], [10,11,12]])
np.concatenate((a, b), axis=0) # column wise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
np.concatenate((a, b), axis=1) #Row wise

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [69]:
np.split(a, 2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [73]:
a==b

array([[False, False, False],
       [False, False, False]])

In [74]:
np.array_equal(a,b)

False